[build]
builder = "nixpacks"
buildCommand = "pnpm install --frozen-lockfile && pnpm run build:railway"

[deploy]
startCommand = "pnpm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
