kind = "web"
previewPath = "/"
title = "VORTEX XMD"
version = "1.0.0"
id = "artifacts/vortex-xmd"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25382

[services.development]
run = "pnpm --filter @workspace/vortex-xmd run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/vortex-xmd", "run", "build" ]
publicDir = "artifacts/vortex-xmd/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25382"
BASE_PATH = "/"
