import { registerCommand } from "../lib/commandLoader";

const jokes = ["Why don't scientists trust atoms? Because they make up everything!", "What do you call a fake noodle? An impasta!", "Why did the scarecrow win an award? Because he was outstanding in his field!"];
const quotes = ["The only way to do great work is to love what you do. — Steve Jobs", "Life is what happens when you're busy making other plans. — John Lennon", "Be the change you wish to see in the world. — Gandhi"];
const facts = ["Honey never expires. Archaeologists found 3000-year-old honey in Egyptian tombs.", "Bananas are berries, but strawberries aren't.", "A group of flamingos is called a flamboyance."];
const roasts = ["You're not stupid; you just have bad luck thinking.", "I'd agree with you, but then we'd both be wrong.", "You're like a software update. Whenever I see you, I think 'not now'."];
const pickups = ["Are you a magician? Because whenever I look at you, everyone else disappears.", "Do you have a map? I keep getting lost in your eyes.", "Is your name Google? Because you have everything I've been searching for."];
const truths = ["What's the most embarrassing thing you've ever done?", "Have you ever lied to your best friend?", "What's your biggest fear?"];
const dares = ["Send a voice note singing your favorite song.", "Change your profile picture for 1 hour.", "Text someone you haven't talked to in months."];

registerCommand({ name: "joke", category: "fun", description: "Get a random joke", handler: async ({ sock, jid }) => { await sock.sendMessage(jid, { text: jokes[Math.floor(Math.random() * jokes.length)] }); } });
registerCommand({ name: "quote", category: "fun", description: "Get a random quote", handler: async ({ sock, jid }) => { await sock.sendMessage(jid, { text: quotes[Math.floor(Math.random() * quotes.length)] }); } });
registerCommand({ name: "fact", category: "fun", description: "Get a random fact", handler: async ({ sock, jid }) => { await sock.sendMessage(jid, { text: facts[Math.floor(Math.random() * facts.length)] }); } });
registerCommand({ name: "8ball", category: "fun", description: "Magic 8-ball", handler: async ({ sock, jid, args }) => { const responses = ["Yes", "No", "Maybe", "Definitely", "Ask again later", "I don't think so", "Absolutely!", "Not a chance"]; const q = args.join(" ") || "your question"; await sock.sendMessage(jid, { text: `🎱 Q: ${q}\n\nA: ${responses[Math.floor(Math.random() * responses.length)]}` }); } });
registerCommand({ name: "coinflip", category: "fun", description: "Flip a coin", handler: async ({ sock, jid }) => { await sock.sendMessage(jid, { text: `🪙 ${Math.random() < 0.5 ? "Heads" : "Tails"}!` }); } });
registerCommand({ name: "dice", category: "fun", description: "Roll a dice", handler: async ({ sock, jid }) => { await sock.sendMessage(jid, { text: `🎲 You rolled: ${Math.floor(Math.random() * 6) + 1}` }); } });
registerCommand({ name: "rps", category: "fun", description: "Rock Paper Scissors", handler: async ({ sock, jid, args }) => { const choices = ["rock", "paper", "scissors"]; const bot = choices[Math.floor(Math.random() * 3)]; const user = args[0]?.toLowerCase(); if (!choices.includes(user)) { await sock.sendMessage(jid, { text: "Usage: .rps rock/paper/scissors" }); return; } const result = user === bot ? "Draw!" : (user === "rock" && bot === "scissors") || (user === "paper" && bot === "rock") || (user === "scissors" && bot === "paper") ? "You win! 🎉" : "I win! 😏"; await sock.sendMessage(jid, { text: `You: ${user}\nBot: ${bot}\n${result}` }); } });
registerCommand({ name: "ship", category: "fun", description: "Ship two people", handler: async ({ sock, jid, args }) => { const pct = Math.floor(Math.random() * 101); await sock.sendMessage(jid, { text: `💕 ${args[0] ?? "Person1"} & ${args[1] ?? "Person2"} = ${pct}% compatible!` }); } });
registerCommand({ name: "truth", category: "fun", description: "Truth question", handler: async ({ sock, jid }) => { await sock.sendMessage(jid, { text: `💬 Truth: ${truths[Math.floor(Math.random() * truths.length)]}` }); } });
registerCommand({ name: "dare", category: "fun", description: "Dare challenge", handler: async ({ sock, jid }) => { await sock.sendMessage(jid, { text: `🎯 Dare: ${dares[Math.floor(Math.random() * dares.length)]}` }); } });
registerCommand({ name: "roast", category: "fun", description: "Get roasted", handler: async ({ sock, jid, args }) => { await sock.sendMessage(jid, { text: `🔥 @${args[0] ?? "you"}: ${roasts[Math.floor(Math.random() * roasts.length)]}` }); } });
registerCommand({ name: "pickup", category: "fun", description: "Pickup line", handler: async ({ sock, jid }) => { await sock.sendMessage(jid, { text: `😉 ${pickups[Math.floor(Math.random() * pickups.length)]}` }); } });
registerCommand({ name: "hack", category: "fun", description: "Fake hack animation", handler: async ({ sock, jid, args }) => { const target = args[0] ?? "the system"; await sock.sendMessage(jid, { text: `💻 Hacking ${target}...\n[████████░░] 80%\nAccess granted! 🔓` }); } });
registerCommand({ name: "simprate", category: "fun", description: "Simp rate checker", handler: async ({ sock, jid, args }) => { await sock.sendMessage(jid, { text: `😂 ${args[0] ?? "You"} is ${Math.floor(Math.random() * 101)}% simp!` }); } });
registerCommand({ name: "love", category: "fun", description: "Love percentage", handler: async ({ sock, jid, args }) => { await sock.sendMessage(jid, { text: `❤️ ${args[0] ?? "You"} love score: ${Math.floor(Math.random() * 101)}%` }); } });
registerCommand({ name: "couple", category: "fun", description: "Couple compatibility", handler: async ({ sock, jid, args }) => { await sock.sendMessage(jid, { text: `💑 ${args[0] ?? "A"} + ${args[1] ?? "B"} = ${Math.floor(Math.random() * 101)}% match!` }); } });
registerCommand({ name: "character", category: "fun", description: "Random character trait", handler: async ({ sock, jid }) => { const traits = ["Brave", "Cunning", "Wise", "Loyal", "Chaotic", "Noble", "Mysterious"]; await sock.sendMessage(jid, { text: `🎭 Your character trait: ${traits[Math.floor(Math.random() * traits.length)]}` }); } });
