import { registerCommand } from "../lib/commandLoader";

const warns: Record<string, Record<string, number>> = {};
const antilink: Set<string> = new Set();
const antibadword: Set<string> = new Set();
const welcomeGroups: Set<string> = new Set();
const goodbyeGroups: Set<string> = new Set();

registerCommand({ name: "kick", category: "group", description: "Kick a member from the group", groupOnly: true, adminOnly: true, usage: ".kick @user", handler: async ({ sock, jid, msg, args }) => { const target = msg.message?.extendedTextMessage?.contextInfo?.participant ?? (args[0] ? args[0].replace(/\D/g, "") + "@s.whatsapp.net" : null); if (!target) { await sock.sendMessage(jid, { text: "⚠️ Mention or provide a user to kick." }); return; } await sock.groupParticipantsUpdate(jid, [target], "remove"); await sock.sendMessage(jid, { text: `✅ Kicked @${target.split("@")[0]}`, mentions: [target] }); } });

registerCommand({ name: "add", category: "group", description: "Add a member to the group", groupOnly: true, adminOnly: true, usage: ".add [phone]", handler: async ({ sock, jid, args }) => { if (!args[0]) { await sock.sendMessage(jid, { text: "⚠️ Provide a phone number to add." }); return; } const num = args[0].replace(/\D/g, "") + "@s.whatsapp.net"; await sock.groupParticipantsUpdate(jid, [num], "add"); await sock.sendMessage(jid, { text: `✅ Added ${args[0]}` }); } });

registerCommand({ name: "promote", category: "group", description: "Promote member to admin", groupOnly: true, adminOnly: true, usage: ".promote @user", handler: async ({ sock, jid, msg, args }) => { const target = msg.message?.extendedTextMessage?.contextInfo?.participant ?? (args[0] ? args[0].replace(/\D/g, "") + "@s.whatsapp.net" : null); if (!target) { await sock.sendMessage(jid, { text: "⚠️ Mention a user to promote." }); return; } await sock.groupParticipantsUpdate(jid, [target], "promote"); await sock.sendMessage(jid, { text: `⬆️ Promoted @${target.split("@")[0]} to admin!`, mentions: [target] }); } });

registerCommand({ name: "demote", category: "group", description: "Demote admin to member", groupOnly: true, adminOnly: true, usage: ".demote @user", handler: async ({ sock, jid, msg, args }) => { const target = msg.message?.extendedTextMessage?.contextInfo?.participant ?? (args[0] ? args[0].replace(/\D/g, "") + "@s.whatsapp.net" : null); if (!target) { await sock.sendMessage(jid, { text: "⚠️ Mention a user to demote." }); return; } await sock.groupParticipantsUpdate(jid, [target], "demote"); await sock.sendMessage(jid, { text: `⬇️ Demoted @${target.split("@")[0]}.`, mentions: [target] }); } });

registerCommand({ name: "mute", category: "group", description: "Mute group (only admins can send)", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { await sock.groupSettingUpdate(jid, "announcement"); await sock.sendMessage(jid, { text: "🔇 Group muted — only admins can send messages." }); } });
registerCommand({ name: "unmute", category: "group", description: "Unmute group for everyone", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { await sock.groupSettingUpdate(jid, "not_announcement"); await sock.sendMessage(jid, { text: "🔊 Group unmuted — everyone can send messages." }); } });

registerCommand({ name: "link", category: "group", description: "Get group invite link", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { const code = await sock.groupInviteCode(jid); await sock.sendMessage(jid, { text: `🔗 *Invite Link:*\nhttps://chat.whatsapp.com/${code}` }); } });
registerCommand({ name: "revoke", category: "group", description: "Revoke group invite link", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { await sock.groupRevokeInvite(jid); await sock.sendMessage(jid, { text: "✅ Invite link has been revoked and a new one generated." }); } });

registerCommand({ name: "groupinfo", category: "group", description: "Get group information", groupOnly: true, handler: async ({ sock, jid }) => { const meta = await sock.groupMetadata(jid); const admins = meta.participants.filter(p => p.admin).length; await sock.sendMessage(jid, { text: [`╭━━━━━━━━━━━━━━━━━━━━╮`, `┃ 📋 GROUP INFO`, `┃ Name: ${meta.subject}`, `┃ Members: ${meta.participants.length}`, `┃ Admins: ${admins}`, `┃ Desc: ${(meta.desc ?? "None").slice(0, 40)}`, `╰━━━━━━━━━━━━━━━━━━━━╯`].join("\n") }); } });

registerCommand({ name: "everyone", aliases: ["tagall"], category: "group", description: "Tag all group members", groupOnly: true, adminOnly: true, handler: async ({ sock, jid, args }) => { const meta = await sock.groupMetadata(jid); const mentions = meta.participants.map(p => p.id); const msg = (args.join(" ") || "Attention everyone!") + "\n" + mentions.map(m => `@${m.split("@")[0]}`).join(" "); await sock.sendMessage(jid, { text: msg, mentions }); } });

registerCommand({ name: "hidetag", category: "group", description: "Tag all members silently", groupOnly: true, adminOnly: true, handler: async ({ sock, jid, args }) => { const meta = await sock.groupMetadata(jid); const mentions = meta.participants.map(p => p.id); await sock.sendMessage(jid, { text: args.join(" ") || "​", mentions }); } });

registerCommand({ name: "warn", category: "group", description: "Warn a user", groupOnly: true, adminOnly: true, usage: ".warn @user [reason]", handler: async ({ sock, jid, args, msg }) => { const target = msg.message?.extendedTextMessage?.contextInfo?.participant ?? (args[0] ? args[0].replace(/\D/g, "") + "@s.whatsapp.net" : null); if (!target) { await sock.sendMessage(jid, { text: "⚠️ Mention a user to warn." }); return; } if (!warns[jid]) warns[jid] = {}; warns[jid][target] = (warns[jid]?.[target] ?? 0) + 1; const count = warns[jid][target]; const reason = args.slice(1).join(" ") || "No reason provided"; await sock.sendMessage(jid, { text: `⚠️ *Warning ${count}/3*\n@${target.split("@")[0]}\nReason: ${reason}${count >= 3 ? "\n\n🚫 Max warnings reached!" : ""}`, mentions: [target] }); if (count >= 3) { await sock.groupParticipantsUpdate(jid, [target], "remove"); warns[jid][target] = 0; } } });

registerCommand({ name: "unwarn", category: "group", description: "Remove a warning from user", groupOnly: true, adminOnly: true, handler: async ({ sock, jid, args, msg }) => { const target = msg.message?.extendedTextMessage?.contextInfo?.participant ?? (args[0] ? args[0].replace(/\D/g, "") + "@s.whatsapp.net" : null); if (!target) { await sock.sendMessage(jid, { text: "⚠️ Mention a user." }); return; } if (warns[jid]?.[target]) warns[jid][target] = Math.max(0, (warns[jid][target] ?? 1) - 1); await sock.sendMessage(jid, { text: `✅ Warning removed from @${target.split("@")[0]}. Current: ${warns[jid]?.[target] ?? 0}/3`, mentions: [target] }); } });

registerCommand({ name: "warnings", category: "group", description: "Check user warnings", groupOnly: true, handler: async ({ sock, jid, args, msg }) => { const target = msg.message?.extendedTextMessage?.contextInfo?.participant ?? (args[0] ? args[0].replace(/\D/g, "") + "@s.whatsapp.net" : null); if (!target) { await sock.sendMessage(jid, { text: "⚠️ Mention a user." }); return; } await sock.sendMessage(jid, { text: `📋 Warnings for @${target.split("@")[0]}: ${warns[jid]?.[target] ?? 0}/3`, mentions: [target] }); } });

registerCommand({ name: "setname", category: "group", description: "Set group name", groupOnly: true, adminOnly: true, usage: ".setname [name]", handler: async ({ sock, jid, args }) => { const name = args.join(" "); if (!name) { await sock.sendMessage(jid, { text: "⚠️ Provide a group name." }); return; } await sock.groupUpdateSubject(jid, name); await sock.sendMessage(jid, { text: `✅ Group name changed to: *${name}*` }); } });
registerCommand({ name: "setdesc", category: "group", description: "Set group description", groupOnly: true, adminOnly: true, usage: ".setdesc [text]", handler: async ({ sock, jid, args }) => { const desc = args.join(" "); await sock.groupUpdateDescription(jid, desc); await sock.sendMessage(jid, { text: "✅ Group description updated." }); } });
registerCommand({ name: "leave", category: "group", description: "Bot leaves the group", groupOnly: true, ownerOnly: true, handler: async ({ sock, jid }) => { await sock.sendMessage(jid, { text: "👋 Goodbye everyone! VORTEX XMD is leaving." }); await sock.groupLeave(jid); } });

registerCommand({ name: "antilink", category: "group", description: "Toggle anti-link protection", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { if (antilink.has(jid)) { antilink.delete(jid); await sock.sendMessage(jid, { text: "🔓 Anti-link *disabled*." }); } else { antilink.add(jid); await sock.sendMessage(jid, { text: "🛡️ Anti-link *enabled* — links will be deleted." }); } } });
registerCommand({ name: "antibadword", category: "group", description: "Toggle anti-bad word filter", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { if (antibadword.has(jid)) { antibadword.delete(jid); await sock.sendMessage(jid, { text: "🔓 Anti-badword *disabled*." }); } else { antibadword.add(jid); await sock.sendMessage(jid, { text: "🛡️ Anti-badword *enabled*." }); } } });
registerCommand({ name: "welcome", category: "group", description: "Toggle welcome message for new members", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { if (welcomeGroups.has(jid)) { welcomeGroups.delete(jid); await sock.sendMessage(jid, { text: "🔕 Welcome messages *disabled*." }); } else { welcomeGroups.add(jid); await sock.sendMessage(jid, { text: "👋 Welcome messages *enabled*." }); } } });
registerCommand({ name: "goodbye", category: "group", description: "Toggle goodbye message for leaving members", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { if (goodbyeGroups.has(jid)) { goodbyeGroups.delete(jid); await sock.sendMessage(jid, { text: "🔕 Goodbye messages *disabled*." }); } else { goodbyeGroups.add(jid); await sock.sendMessage(jid, { text: "👋 Goodbye messages *enabled*." }); } } });

export { antilink, antibadword, welcomeGroups, goodbyeGroups };
