import { registerCommand } from "../lib/commandLoader";


registerCommand({ name: "kick", category: "group", description: "Kick a member", groupOnly: true, adminOnly: true, handler: async ({ sock, jid, msg, args }) => { const target = msg.message?.extendedTextMessage?.contextInfo?.participant ?? args[0]; if (!target) { await sock.sendMessage(jid, { text: "Mention or provide a user to kick." }); return; } await sock.groupParticipantsUpdate(jid, [target], "remove"); await sock.sendMessage(jid, { text: `✅ Kicked @${target.split("@")[0]}`, mentions: [target] }); } });
registerCommand({ name: "add", category: "group", description: "Add a member", groupOnly: true, adminOnly: true, handler: async ({ sock, jid, args }) => { if (!args[0]) { await sock.sendMessage(jid, { text: "Provide a phone number to add." }); return; } const num = args[0].replace(/\D/g, "") + "@s.whatsapp.net"; await sock.groupParticipantsUpdate(jid, [num], "add"); await sock.sendMessage(jid, { text: `✅ Added ${args[0]}` }); } });
registerCommand({ name: "promote", category: "group", description: "Promote to admin", groupOnly: true, adminOnly: true, handler: async ({ sock, jid, msg, args }) => { const target = msg.message?.extendedTextMessage?.contextInfo?.participant ?? args[0] + "@s.whatsapp.net"; await sock.groupParticipantsUpdate(jid, [target], "promote"); await sock.sendMessage(jid, { text: `✅ Promoted @${target.split("@")[0]}`, mentions: [target] }); } });
registerCommand({ name: "demote", category: "group", description: "Demote from admin", groupOnly: true, adminOnly: true, handler: async ({ sock, jid, msg, args }) => { const target = msg.message?.extendedTextMessage?.contextInfo?.participant ?? args[0] + "@s.whatsapp.net"; await sock.groupParticipantsUpdate(jid, [target], "demote"); await sock.sendMessage(jid, { text: `✅ Demoted @${target.split("@")[0]}`, mentions: [target] }); } });
registerCommand({ name: "mute", category: "group", description: "Mute group (only admins can send)", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { await sock.groupSettingUpdate(jid, "announcement"); await sock.sendMessage(jid, { text: "🔇 Group muted — only admins can send messages." }); } });
registerCommand({ name: "unmute", category: "group", description: "Unmute group", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { await sock.groupSettingUpdate(jid, "not_announcement"); await sock.sendMessage(jid, { text: "🔊 Group unmuted." }); } });
registerCommand({ name: "link", category: "group", description: "Get group invite link", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { const code = await sock.groupInviteCode(jid); await sock.sendMessage(jid, { text: `🔗 Invite link:\nhttps://chat.whatsapp.com/${code}` }); } });
registerCommand({ name: "revoke", category: "group", description: "Revoke group invite link", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { await sock.groupRevokeInvite(jid); await sock.sendMessage(jid, { text: "✅ Invite link revoked." }); } });
registerCommand({ name: "groupinfo", category: "group", description: "Get group info", groupOnly: true, handler: async ({ sock, jid }) => { const meta = await sock.groupMetadata(jid); await sock.sendMessage(jid, { text: `📋 *${meta.subject}*\n👥 Members: ${meta.participants.length}\n📝 Desc: ${meta.desc ?? "None"}` }); } });
registerCommand({ name: "everyone", aliases: ["tagall"], category: "group", description: "Tag all members", groupOnly: true, adminOnly: true, handler: async ({ sock, jid, args }) => { const meta = await sock.groupMetadata(jid); const mentions = meta.participants.map(p => p.id); const text = (args.join(" ") || "Attention!") + "\n" + mentions.map(m => `@${m.split("@")[0]}`).join(" "); await sock.sendMessage(jid, { text, mentions }); } });
registerCommand({ name: "hidetag", category: "group", description: "Tag all silently", groupOnly: true, adminOnly: true, handler: async ({ sock, jid, args }) => { const meta = await sock.groupMetadata(jid); const mentions = meta.participants.map(p => p.id); await sock.sendMessage(jid, { text: args.join(" ") || "​", mentions }); } });
registerCommand({ name: "setname", category: "group", description: "Set group name", groupOnly: true, adminOnly: true, handler: async ({ sock, jid, args }) => { const name = args.join(" "); await sock.groupUpdateSubject(jid, name); await sock.sendMessage(jid, { text: `✅ Group name set to: ${name}` }); } });
registerCommand({ name: "setdesc", category: "group", description: "Set group description", groupOnly: true, adminOnly: true, handler: async ({ sock, jid, args }) => { const desc = args.join(" "); await sock.groupUpdateDescription(jid, desc); await sock.sendMessage(jid, { text: `✅ Group description updated.` }); } });
registerCommand({ name: "leave", category: "group", description: "Bot leaves the group", groupOnly: true, ownerOnly: true, handler: async ({ sock, jid }) => { await sock.sendMessage(jid, { text: "👋 Goodbye!" }); await sock.groupLeave(jid); } });
registerCommand({ name: "warn", category: "group", description: "Warn a user", groupOnly: true, adminOnly: true, handler: async ({ sock, jid, args, msg }) => { const target = msg.message?.extendedTextMessage?.contextInfo?.participant ?? args[0]; await sock.sendMessage(jid, { text: `⚠️ @${(target ?? "").split("@")[0]} has been warned!`, mentions: target ? [target] : [] }); } });
registerCommand({ name: "unwarn", category: "group", description: "Remove warning", groupOnly: true, adminOnly: true, handler: async ({ sock, jid, args }) => { await sock.sendMessage(jid, { text: `✅ Warning removed for ${args[0] ?? "user"}.` }); } });
registerCommand({ name: "warnings", category: "group", description: "Check warnings", groupOnly: true, handler: async ({ sock, jid, args }) => { await sock.sendMessage(jid, { text: `📋 Warnings for ${args[0] ?? "user"}: 0` }); } });
registerCommand({ name: "antilink", category: "group", description: "Toggle anti-link", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { await sock.sendMessage(jid, { text: "🛡️ Anti-link toggled." }); } });
registerCommand({ name: "antibadword", category: "group", description: "Toggle anti-bad word", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { await sock.sendMessage(jid, { text: "🛡️ Anti-bad word toggled." }); } });
registerCommand({ name: "welcome", category: "group", description: "Toggle welcome message", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { await sock.sendMessage(jid, { text: "👋 Welcome message toggled." }); } });
registerCommand({ name: "goodbye", category: "group", description: "Toggle goodbye message", groupOnly: true, adminOnly: true, handler: async ({ sock, jid }) => { await sock.sendMessage(jid, { text: "👋 Goodbye message toggled." }); } });
