import { registerCommand } from "../lib/commandLoader";

const searchStub = (name: string) => async ({ sock, jid, args }: Parameters<Parameters<typeof registerCommand>[0]["handler"]>[0]) => {
  await sock.sendMessage(jid, { text: `🔍 ${name} search: "${args.join(" ")}" — integrate ${name} API for results.` });
};

registerCommand({ name: "google", category: "search", description: "Search Google", handler: searchStub("Google") });
registerCommand({ name: "npm", category: "search", description: "Search NPM packages", handler: async ({ sock, jid, args }) => { try { const res = await fetch(`https://registry.npmjs.org/-/v1/search?text=${encodeURIComponent(args.join(" "))}&size=5`); const d = await res.json() as { objects?: Array<{ package?: { name?: string; description?: string; version?: string } }> }; const results = d.objects?.map(o => `📦 *${o.package?.name}* v${o.package?.version}\n${o.package?.description ?? ""}`).join("\n\n") ?? "No results."; await sock.sendMessage(jid, { text: results }); } catch { await sock.sendMessage(jid, { text: "❌ NPM search failed." }); } } });
registerCommand({ name: "pinterest", category: "search", description: "Search Pinterest", handler: searchStub("Pinterest") });
registerCommand({ name: "image", category: "search", description: "Search images", handler: searchStub("Image") });
registerCommand({ name: "movie", category: "search", description: "Search movies", handler: async ({ sock, jid, args }) => { try { const res = await fetch(`https://www.omdbapi.com/?t=${encodeURIComponent(args.join(" "))}&apikey=trilogy`); const d = await res.json() as { Title?: string; Year?: string; Plot?: string; imdbRating?: string; Response?: string }; if (d.Response === "False") { await sock.sendMessage(jid, { text: "Movie not found." }); return; } await sock.sendMessage(jid, { text: `🎬 *${d.Title}* (${d.Year})\n⭐ ${d.imdbRating}/10\n📖 ${d.Plot}` }); } catch { await sock.sendMessage(jid, { text: "❌ Movie search failed." }); } } });
registerCommand({ name: "song", category: "search", description: "Search songs", handler: searchStub("Song") });
registerCommand({ name: "lyrics", category: "search", description: "Search lyrics", handler: searchStub("Lyrics") });
registerCommand({ name: "wallpaper", category: "search", description: "Search wallpapers", handler: searchStub("Wallpaper") });
registerCommand({ name: "anime", category: "search", description: "Search anime info", handler: async ({ sock, jid, args }) => { try { const res = await fetch(`https://api.jikan.moe/v4/anime?q=${encodeURIComponent(args.join(" "))}&limit=1`); const d = await res.json() as { data?: Array<{ title?: string; score?: number; synopsis?: string }> }; const anime = d.data?.[0]; if (!anime) { await sock.sendMessage(jid, { text: "Anime not found." }); return; } await sock.sendMessage(jid, { text: `🎌 *${anime.title}*\n⭐ Score: ${anime.score}\n📖 ${anime.synopsis?.slice(0, 300)}...` }); } catch { await sock.sendMessage(jid, { text: "❌ Anime search failed." }); } } });
registerCommand({ name: "manga", category: "search", description: "Search manga", handler: async ({ sock, jid, args }) => { try { const res = await fetch(`https://api.jikan.moe/v4/manga?q=${encodeURIComponent(args.join(" "))}&limit=1`); const d = await res.json() as { data?: Array<{ title?: string; score?: number; synopsis?: string }> }; const manga = d.data?.[0]; if (!manga) { await sock.sendMessage(jid, { text: "Manga not found." }); return; } await sock.sendMessage(jid, { text: `📚 *${manga.title}*\n⭐ Score: ${manga.score}\n📖 ${manga.synopsis?.slice(0, 300)}...` }); } catch { await sock.sendMessage(jid, { text: "❌ Manga search failed." }); } } });
