import { registerCommand } from "../lib/commandLoader";
import { createHash } from "crypto";
import { v4 as uuidv4 } from "uuid";

registerCommand({ name: "iplookup", aliases: ["ip"], category: "tools", description: "IP address lookup", handler: async ({ sock, jid, args }) => { try { const ip = args[0] ?? "8.8.8.8"; const res = await fetch(`http://ip-api.com/json/${ip}`); const d = await res.json() as { country?: string; city?: string; isp?: string; query?: string; org?: string }; await sock.sendMessage(jid, { text: `🌐 IP: ${d.query}\n🏳️ Country: ${d.country}\n🏙️ City: ${d.city}\n📡 ISP: ${d.isp}\n🏢 Org: ${d.org}` }); } catch { await sock.sendMessage(jid, { text: "❌ IP lookup failed." }); } } });
registerCommand({ name: "whois", category: "tools", description: "Domain WHOIS lookup", handler: async ({ sock, jid, args }) => { await sock.sendMessage(jid, { text: `🔍 WHOIS for ${args[0] ?? "example.com"}: Integrate WHOIS API.` }); } });
registerCommand({ name: "dns", category: "tools", description: "DNS lookup", handler: async ({ sock, jid, args }) => { try { const domain = args[0] ?? "google.com"; const res = await fetch(`https://dns.google/resolve?name=${domain}&type=A`); const d = await res.json() as { Answer?: Array<{ data?: string }> }; const ips = d.Answer?.map(a => a.data).join(", ") ?? "No records."; await sock.sendMessage(jid, { text: `🌐 DNS for ${domain}:\n${ips}` }); } catch { await sock.sendMessage(jid, { text: "❌ DNS lookup failed." }); } } });
registerCommand({ name: "pinghost", category: "tools", description: "Ping a host (HTTP check)", handler: async ({ sock, jid, args }) => { const host = args[0] ?? "google.com"; const start = Date.now(); try { await fetch(`https://${host}`, { signal: AbortSignal.timeout(5000) }); await sock.sendMessage(jid, { text: `🏓 ${host} — ${Date.now() - start}ms` }); } catch { await sock.sendMessage(jid, { text: `❌ ${host} unreachable.` }); } } });
registerCommand({ name: "portscan", category: "tools", description: "Port scan info", handler: async ({ sock, jid, args }) => { await sock.sendMessage(jid, { text: `🔍 Port scan for ${args[0] ?? "localhost"}: Common ports — 80 (HTTP), 443 (HTTPS), 22 (SSH), 3306 (MySQL)` }); } });
registerCommand({ name: "encode", category: "tools", description: "Encode text (URL/Base64)", handler: async ({ sock, jid, args }) => { const [type, ...rest] = args; const text = rest.join(" "); const result = type === "url" ? encodeURIComponent(text) : Buffer.from(text).toString("base64"); await sock.sendMessage(jid, { text: `🔐 Encoded: ${result}` }); } });
registerCommand({ name: "decode", category: "tools", description: "Decode text (URL/Base64)", handler: async ({ sock, jid, args }) => { const [type, ...rest] = args; const text = rest.join(" "); try { const result = type === "url" ? decodeURIComponent(text) : Buffer.from(text, "base64").toString("utf-8"); await sock.sendMessage(jid, { text: `🔓 Decoded: ${result}` }); } catch { await sock.sendMessage(jid, { text: "❌ Decode failed." }); } } });
registerCommand({ name: "hash", category: "tools", description: "Hash text (md5/sha256/sha1)", handler: async ({ sock, jid, args }) => { const [algo, ...rest] = args; const text = rest.join(" "); const validAlgos = ["md5", "sha256", "sha1", "sha512"]; const a = validAlgos.includes(algo) ? algo : "sha256"; const h = createHash(a).update(text).digest("hex"); await sock.sendMessage(jid, { text: `#️⃣ ${a.toUpperCase()}: ${h}` }); } });
